### ISSUE TITLE
The code in provided pip package is not complete and have bugs.

### ISSUE THREAD

**Issue by xyzustc** [SymbioticLab/Fluid#2]
## My env
A 8-gpus local server.  `Python 3.7.11`. `ray 0.8.5`. `fluidexec 0.1.0rc0`. I clone this repo, and my current path is `Fluid/workloads`.

## 1. found these probelms when using the pip package provided.
- in `Fluid/README.md`.
  
  `from fluid.executor import FluidExecutor` fails, cause no `FluidExecutor` in file `executor.py` of that package. It should be `from fluid.fluid_executor import FluidExecutor`.
- in `Fluid/workloads/test_fluid.py`.
  
  In line 13, `from fluid.executor import MyRayTrialExecutor` is not Fluid implementation, but just a simpler wrapper of `class MyRayTrialExecutor(RayTrialExecutor):`. So the `Fluid/workloads/test_fluid.py` is not really testing Fluid's implementation?
- some code in pip package is not completed.
  
  For example, function `_ensure_W` not completed in `fluid_exector.py` of pip package, but completed in `fluid_exector.py` of github repo. And function `debug_string()`.
- some bugs in pip package.
  
  For example, function `_detect_groups()` in `fluid_exector.py` of pip package,`self._find_group(p.trial.trial_id)` should be `self._find_group(p.trial)`. 

  And `assigned, unassigned= partition(self.jobs_pending, lambda p: p.trial.trial_id in self.trial_groups)` should be `unassigned, assigned  = partition(self.jobs_pending, lambda p: p.trial.trial_id in self.trial_groups)`.

  And `self.trial_groups[p.trial.trial_id] = TrialAndGroup(p.trial, grp)` should be `self.trial_groups[p.trial.trial_id] = TrialAndGroup(p.trial, meta.grp)`. 

  But these bugs are fixed in `fluid_exector.py` of github repo.

So, maybe the pip package used older developing version code.

Now, I am importing directly from the fluid files provided in github repo. But still having some problems, I'd like to discuss in another issue.

**Comment by Aetf** [comment]
I'll fix the README and publish a new version on pip after I fix the CI.

`Fluid/workloads/test_fluid.py` was used in early development and shouldn't be included in the repo.

I'm closing this for now. Please feel free to open a new one if you find anything not fixed in the repo.

**Comment by xyzustc** [comment]
Hi, the CI seems to have been fixed. Is the pip package avaliable now?
